version: '3.9'
services:
  bot:
    build: ./bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - redis
  web:
    build: ./web
    ports:
      - '3000:3000'
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
